#!/usr/bin/env bash
# Launch PX4 SITL, Gazebo Harmonic, the down-camera bridge, and rqt_image_view.
# This script intentionally stays in the foreground to own and clean up its child
# process groups when the user presses Ctrl+C.

set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PX4_DIR="$PROJECT_ROOT/PX4-Autopilot"
CONFIG_DIR="$PROJECT_ROOT/config"
LOG_DIR="$PROJECT_ROOT/logs"
PID_FILE="$LOG_DIR/run_all.pids"
SPAWN_INFO_FILE="$LOG_DIR/active_annulus_spawn.env"
LAUNCH_LOG="$LOG_DIR/launcher.log"
PX4_LOG="$LOG_DIR/px4.log"
BRIDGE_LOG="$LOG_DIR/bridge.log"
RQT_LOG="$LOG_DIR/rqt_image_view.log"
ENV_LOG="$LOG_DIR/environment_check.txt"
PX4_READY_FILE=""
BRIDGE_CONFIG="$CONFIG_DIR/down_camera_bridge.yaml"
CYCLONE_CONFIG="$CONFIG_DIR/cyclonedds.xml"
IMAGE_TOPIC=""
CAMERA_INFO_TOPIC=""
PX4_PID=""
BRIDGE_PID=""
RQT_PID=""
EXISTING_GZ_GUI_PIDS=()
cleanup_started=0
SPAWN_SEED=""
START_RQT=1
MOVING_QR=0
MOVING_QR_SPEED=0.08
MOVING_QR_HEADING_DEG=0.0
TRAJECTORY_SEED=""
EVALUATION_DIFFICULTY="medium"

mkdir -p "$LOG_DIR" "$CONFIG_DIR" "$PROJECT_ROOT/artifacts/screenshots"

timestamp() { date '+%Y-%m-%dT%H:%M:%S%z'; }
log() { printf '[%s] %s\n' "$(timestamp)" "$*" | tee -a "$LAUNCH_LOG"; }
fail() { log "ERROR: $*"; exit 1; }

collect_environment() {
  {
    echo "Captured: $(timestamp)"
    echo '=== lsb_release ==='; lsb_release -a 2>&1
    echo '=== uname ==='; uname -a
    echo '=== session ==='; echo "${XDG_SESSION_TYPE:-unset}"
    echo '=== python ==='; python3 --version
    echo '=== git ==='; git --version
    echo '=== ros2 ==='; ros2 --help 2>&1 | head -n 2
    echo '=== gazebo ==='; gz sim --versions 2>&1 || gz --versions 2>&1 || true
    echo '=== cmake ==='; cmake --version | head -n1
    echo '=== graphics ==='; lspci 2>/dev/null | grep -Ei 'vga|3d|display' || true
    echo '=== nvidia ==='; nvidia-smi 2>&1 || true
  } > "$ENV_LOG"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command is unavailable: $1"
}

record_pid() {
  printf '%s=%s\n' "$1" "$2" >> "$PID_FILE"
}

record_new_gazebo_gui() {
  local pid existing already_known
  while IFS= read -r pid; do
    [[ "$pid" =~ ^[0-9]+$ ]] || continue
    already_known=0
    for existing in "${EXISTING_GZ_GUI_PIDS[@]}"; do
      [[ "$pid" == "$existing" ]] && already_known=1 && break
    done
    [[ "$already_known" -eq 0 ]] && record_pid gz_gui "$pid"
  done < <(pgrep -f '^gz sim -g([[:space:]]|$)' 2>/dev/null || true)
}

stop_own_processes() {
  if [[ "$cleanup_started" -eq 1 ]]; then
    return
  fi
  cleanup_started=1
  log 'Stopping project processes.'
  "$PROJECT_ROOT/scripts/stop_all.sh" --quiet || true
}

on_exit() {
  local status=$?
  stop_own_processes
  exit "$status"
}

wait_for_gazebo_image_topic() {
  local deadline candidate info preferred
  deadline=$((SECONDS + 90))

  while (( SECONDS < deadline )); do
    while IFS= read -r candidate; do
      [[ "$candidate" == */image ]] || continue
      info="$(gz topic -i -t "$candidate" 2>&1 || true)"
      grep -q 'gz.msgs.Image' <<< "$info" || continue

      if [[ -z "$IMAGE_TOPIC" ]]; then
        IMAGE_TOPIC="$candidate"
      fi

      preferred="$candidate"
      if [[ "$preferred" == *camera_link* || "$preferred" == *mono_cam* ]]; then
        IMAGE_TOPIC="$preferred"
        break 2
      fi
    done < <(gz topic -l 2>/dev/null || true)

    [[ -n "$IMAGE_TOPIC" ]] && break
    sleep 1
  done

  [[ -n "$IMAGE_TOPIC" ]] || return 1
  CAMERA_INFO_TOPIC="${IMAGE_TOPIC%/image}/camera_info"
  if ! gz topic -i -t "$CAMERA_INFO_TOPIC" 2>&1 | grep -q 'gz.msgs.CameraInfo'; then
    CAMERA_INFO_TOPIC=""
  fi
}

write_bridge_config() {
  {
    cat <<EOF
# Auto-generated by scripts/run_all.sh from the live Gazebo topic discovery.
- ros_topic_name: "/down_camera/image_raw"
  gz_topic_name: "$IMAGE_TOPIC"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  lazy: false
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
EOF
    if [[ -n "$CAMERA_INFO_TOPIC" ]]; then
      cat <<EOF
- ros_topic_name: "/down_camera/camera_info"
  gz_topic_name: "$CAMERA_INFO_TOPIC"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  lazy: false
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
EOF
    fi
  } > "$BRIDGE_CONFIG"
}

start_bridge() {
  local -a bridge_args remap_args
  bridge_args=("$IMAGE_TOPIC@sensor_msgs/msg/Image[gz.msgs.Image")
  remap_args=(-r "$IMAGE_TOPIC:=/down_camera/image_raw")

  if [[ -n "$CAMERA_INFO_TOPIC" ]]; then
    bridge_args+=("$CAMERA_INFO_TOPIC@sensor_msgs/msg/CameraInfo[gz.msgs.CameraInfo")
    remap_args+=(-r "$CAMERA_INFO_TOPIC:=/down_camera/camera_info")
  fi

  # Newer ros_gz_bridge releases accept the YAML directly. The Harmonic
  # package shipped for Humble uses the equivalent established CLI syntax.
  if ros2 run ros_gz_bridge parameter_bridge --help 2>&1 | grep -q 'config_file'; then
    setsid ros2 run ros_gz_bridge parameter_bridge --ros-args \
      -p "config_file:=$BRIDGE_CONFIG" >> "$BRIDGE_LOG" 2>&1 &
  else
    setsid ros2 run ros_gz_bridge parameter_bridge "${bridge_args[@]}" \
      --ros-args "${remap_args[@]}" >> "$BRIDGE_LOG" 2>&1 &
  fi
  BRIDGE_PID=$!
  record_pid bridge "$BRIDGE_PID"
}

wait_for_ros_image() {
  local deadline topic_type
  deadline=$((SECONDS + 45))
  while (( SECONDS < deadline )); do
    topic_type="$(ros2 topic type /down_camera/image_raw 2>/dev/null || true)"
    if [[ "$topic_type" == 'sensor_msgs/msg/Image' ]]; then
      if timeout 8 ros2 topic hz /down_camera/image_raw > "$LOG_DIR/camera_validation.tmp" 2>&1 || true; then
        :
      fi
      if grep -q 'average rate:' "$LOG_DIR/camera_validation.tmp"; then
        mv "$LOG_DIR/camera_validation.tmp" "$LOG_DIR/camera_validation.txt"
        return 0
      fi
    fi
    sleep 1
  done
  rm -f "$LOG_DIR/camera_validation.tmp"
  return 1
}

wait_for_px4_mavlink() {
  # A camera image can be published while PX4 is still booting.  The
  # inference controller talks to PX4 over MAVLink, so expose readiness only
  # after PX4's startup script has created the localhost MAVLink endpoint.
  local deadline
  deadline=$((SECONDS + 90))
  while (( SECONDS < deadline )); do
    if rg -q 'Startup script returned successfully' "$PX4_LOG" 2>/dev/null; then
      [[ -z "$PX4_READY_FILE" ]] || : > "$PX4_READY_FILE"
      return 0
    fi
    kill -0 "$PX4_PID" 2>/dev/null || return 1
    sleep 1
  done
  return 1
}

main() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --spawn-seed)
        [[ $# -ge 2 ]] || fail '--spawn-seed requires an integer.'
        SPAWN_SEED=$2
        shift 2
        ;;
      --no-rqt)
        START_RQT=0
        shift
        ;;
      --moving-qr)
        MOVING_QR=1
        shift
        ;;
      --moving-qr-speed)
        [[ $# -ge 2 ]] || fail '--moving-qr-speed requires metres per second.'
        MOVING_QR_SPEED=$2
        shift 2
        ;;
      --moving-qr-heading-deg)
        [[ $# -ge 2 ]] || fail '--moving-qr-heading-deg requires degrees.'
        MOVING_QR_HEADING_DEG=$2
        shift 2
        ;;
      --trajectory-seed)
        [[ $# -ge 2 ]] || fail '--trajectory-seed requires a non-negative integer.'
        TRAJECTORY_SEED=$2
        shift 2
        ;;
      --evaluation-difficulty)
        [[ $# -ge 2 ]] || fail '--evaluation-difficulty requires easy, medium, or hard.'
        EVALUATION_DIFFICULTY=$2
        shift 2
        ;;
      --px4-ready-file)
        [[ $# -ge 2 ]] || fail '--px4-ready-file requires a path.'
        PX4_READY_FILE=$2
        shift 2
        ;;
      *)
        fail "Unknown argument: $1"
        ;;
    esac
  done
  : > "$LAUNCH_LOG"
  : > "$PX4_LOG"
  : > "$BRIDGE_LOG"
  : > "$RQT_LOG"
  [[ -z "$PX4_READY_FILE" ]] || rm -f "$PX4_READY_FILE"

  [[ -f /etc/os-release ]] || fail 'Cannot determine the operating system.'
  # shellcheck disable=SC1091
  . /etc/os-release
  [[ "${VERSION_ID:-}" == '22.04' ]] || fail "Ubuntu 22.04 is required; found ${PRETTY_NAME:-unknown}."
  [[ -f /opt/ros/humble/setup.bash ]] || fail 'ROS 2 Humble setup file is missing: /opt/ros/humble/setup.bash'
  [[ -d "$PX4_DIR" ]] || fail "PX4 directory is missing: $PX4_DIR"
  [[ -f "$CYCLONE_CONFIG" ]] || fail "Cyclone DDS configuration is missing: $CYCLONE_CONFIG"

  # ROS Humble's generated setup scripts reference optional shell variables;
  # temporarily relax nounset so this works from a completely fresh shell.
  set +u
  # shellcheck disable=SC1091
  source /opt/ros/humble/setup.bash
  set -u
  export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  export CYCLONEDDS_URI="file://$CYCLONE_CONFIG"

  require_command gz
  require_command ros2
  require_command setsid
  ros2 pkg prefix ros_gz_bridge >/dev/null 2>&1 || fail 'ros_gz_bridge is not installed.'
  ros2 pkg prefix rqt_image_view >/dev/null 2>&1 || fail 'rqt_image_view is not installed.'
  ros2 pkg prefix rmw_cyclonedds_cpp >/dev/null 2>&1 || fail 'rmw_cyclonedds_cpp is not installed.'
  collect_environment

  [[ -n "$SPAWN_SEED" ]] || SPAWN_SEED=$(( $(date +%s) % 2147483647 ))
  [[ "$SPAWN_SEED" =~ ^[0-9]+$ ]] || fail '--spawn-seed must be a non-negative integer.'
  [[ "$MOVING_QR_SPEED" =~ ^([0-9]+([.][0-9]*)?|[.][0-9]+)$ ]] || fail '--moving-qr-speed must be non-negative.'
  [[ "$MOVING_QR_HEADING_DEG" =~ ^-?([0-9]+([.][0-9]*)?|[.][0-9]+)$ ]] || fail '--moving-qr-heading-deg must be numeric.'
  [[ -z "$TRAJECTORY_SEED" || "$TRAJECTORY_SEED" =~ ^[0-9]+$ ]] || fail '--trajectory-seed must be a non-negative integer.'
  [[ "$EVALUATION_DIFFICULTY" =~ ^(easy|medium|hard)$ ]] || fail '--evaluation-difficulty must be easy, medium, or hard.'
  # A new spawn receives a new seeded-but-reproducible smooth target path.
  # Passing --trajectory-seed lets a recorded run be replayed exactly.
  [[ -n "$TRAJECTORY_SEED" ]] || TRAJECTORY_SEED=$(( (SPAWN_SEED + 104729) % 2147483647 ))
  export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"
  /usr/bin/python3 "$PROJECT_ROOT/scripts/generate_landing_zone_rings.py" >> "$LAUNCH_LOG" 2>&1
  read -r SPAWN_X SPAWN_Y SPAWN_RADIUS SPAWN_HEADING < <(/usr/bin/python3 "$PROJECT_ROOT/scripts/sample_annulus_spawn.py" --seed "$SPAWN_SEED")
  read -r PROFILE_SEED PROFILE_HEADING_DEG PROFILE_BASE_SPEED PROFILE_SPEED_AMPLITUDE PROFILE_SPEED_FREQUENCY PROFILE_SPEED_PHASE PROFILE_LATERAL_AMPLITUDE PROFILE_TURN_FREQUENCY PROFILE_TURN_PHASE PROFILE_WAVE_ROLL_DEG PROFILE_WAVE_PITCH_DEG PROFILE_WAVE_YAW_DEG PROFILE_WAVE_HEAVE_M PROFILE_WAVE_ROLL_FREQUENCY PROFILE_WAVE_PITCH_FREQUENCY PROFILE_WAVE_YAW_FREQUENCY PROFILE_WAVE_HEAVE_FREQUENCY PROFILE_WAVE_PHASE < <(
    /usr/bin/python3 "$PROJECT_ROOT/landing_rl/scenario.py" --seed "$TRAJECTORY_SEED" --wavy-motion-profile --motion-profile "$EVALUATION_DIFFICULTY"
  )
  read -r TARGET_VX TARGET_VY < <(/usr/bin/python3 - "$TRAJECTORY_SEED" "$EVALUATION_DIFFICULTY" <<'PY'
from landing_rl.scenario import random_evaluation_motion_profile
import sys
vx, vy = random_evaluation_motion_profile(int(sys.argv[1]), sys.argv[2]).velocity_at(0.0)
print(f"{vx:.6f} {vy:.6f}")
PY
)
  {
    printf 'SPAWN_SEED=%q\n' "$SPAWN_SEED"
    printf 'SPAWN_X=%q\n' "$SPAWN_X"
    printf 'SPAWN_Y=%q\n' "$SPAWN_Y"
    printf 'SPAWN_RADIUS=%q\n' "$SPAWN_RADIUS"
    printf 'SPAWN_HEADING=%q\n' "$SPAWN_HEADING"
    printf 'MOVING_QR=%q\n' "$MOVING_QR"
    printf 'TARGET_SPEED_MPS=%q\n' "$PROFILE_BASE_SPEED"
    printf 'TARGET_HEADING_DEG=%q\n' "$PROFILE_HEADING_DEG"
    printf 'TARGET_VX=%q\n' "$TARGET_VX"
    printf 'TARGET_VY=%q\n' "$TARGET_VY"
    printf 'TRAJECTORY_SEED=%q\n' "$TRAJECTORY_SEED"
    printf 'EVALUATION_DIFFICULTY=%q\n' "$EVALUATION_DIFFICULTY"
    printf 'TRAJECTORY_HEADING_DEG=%q\n' "$PROFILE_HEADING_DEG"
    printf 'TRAJECTORY_BASE_SPEED_MPS=%q\n' "$PROFILE_BASE_SPEED"
    printf 'TRAJECTORY_SPEED_AMPLITUDE_MPS=%q\n' "$PROFILE_SPEED_AMPLITUDE"
    printf 'TRAJECTORY_SPEED_FREQUENCY_RADPS=%q\n' "$PROFILE_SPEED_FREQUENCY"
    printf 'TRAJECTORY_SPEED_PHASE_RAD=%q\n' "$PROFILE_SPEED_PHASE"
    printf 'TRAJECTORY_LATERAL_AMPLITUDE_MPS=%q\n' "$PROFILE_LATERAL_AMPLITUDE"
    printf 'TRAJECTORY_TURN_FREQUENCY_RADPS=%q\n' "$PROFILE_TURN_FREQUENCY"
    printf 'TRAJECTORY_TURN_PHASE_RAD=%q\n' "$PROFILE_TURN_PHASE"
    printf 'WAVE_ROLL_DEG=%q\n' "$PROFILE_WAVE_ROLL_DEG"
    printf 'WAVE_PITCH_DEG=%q\n' "$PROFILE_WAVE_PITCH_DEG"
    printf 'WAVE_YAW_DEG=%q\n' "$PROFILE_WAVE_YAW_DEG"
    printf 'WAVE_HEAVE_M=%q\n' "$PROFILE_WAVE_HEAVE_M"
  } > "$SPAWN_INFO_FILE"
  log "Random annulus spawn seed=$SPAWN_SEED pose=($SPAWN_X, $SPAWN_Y, 0), radius=${SPAWN_RADIUS} m."

  "$PROJECT_ROOT/scripts/stop_all.sh" --quiet || true
  : > "$PID_FILE"
  mapfile -t EXISTING_GZ_GUI_PIDS < <(pgrep -f '^gz sim -g([[:space:]]|$)' 2>/dev/null || true)
  trap on_exit EXIT INT TERM

  WORLD_NAME=aruco
  if [[ "$MOVING_QR" -eq 1 ]]; then
    WORLD_NAME=aruco_moving_qr
    export PX4_GZ_PLATFORM_VEL="$PROFILE_BASE_SPEED"
    export PX4_GZ_PLATFORM_HEADING_DEG="$PROFILE_HEADING_DEG"
    export PX4_GZ_TRAJECTORY_BASE_SPEED_MPS="$PROFILE_BASE_SPEED"
    export PX4_GZ_TRAJECTORY_SPEED_AMPLITUDE_MPS="$PROFILE_SPEED_AMPLITUDE"
    export PX4_GZ_TRAJECTORY_SPEED_FREQUENCY_RADPS="$PROFILE_SPEED_FREQUENCY"
    export PX4_GZ_TRAJECTORY_SPEED_PHASE_RAD="$PROFILE_SPEED_PHASE"
    export PX4_GZ_TRAJECTORY_LATERAL_AMPLITUDE_MPS="$PROFILE_LATERAL_AMPLITUDE"
    export PX4_GZ_TRAJECTORY_TURN_FREQUENCY_RADPS="$PROFILE_TURN_FREQUENCY"
    export PX4_GZ_TRAJECTORY_TURN_PHASE_RAD="$PROFILE_TURN_PHASE"
    export PX4_GZ_WAVE_ROLL_DEG="$PROFILE_WAVE_ROLL_DEG"
    export PX4_GZ_WAVE_PITCH_DEG="$PROFILE_WAVE_PITCH_DEG"
    export PX4_GZ_WAVE_YAW_DEG="$PROFILE_WAVE_YAW_DEG"
    export PX4_GZ_WAVE_HEAVE_M="$PROFILE_WAVE_HEAVE_M"
    export PX4_GZ_WAVE_ROLL_FREQUENCY_RADPS="$PROFILE_WAVE_ROLL_FREQUENCY"
    export PX4_GZ_WAVE_PITCH_FREQUENCY_RADPS="$PROFILE_WAVE_PITCH_FREQUENCY"
    export PX4_GZ_WAVE_YAW_FREQUENCY_RADPS="$PROFILE_WAVE_YAW_FREQUENCY"
    export PX4_GZ_WAVE_HEAVE_FREQUENCY_RADPS="$PROFILE_WAVE_HEAVE_FREQUENCY"
    export PX4_GZ_WAVE_PHASE_RAD="$PROFILE_WAVE_PHASE"
  log "Starting ${EVALUATION_DIFFICULTY} held-out QR path seed=${TRAJECTORY_SEED}: ${PROFILE_BASE_SPEED} m/s base, heading ${PROFILE_HEADING_DEG} deg, boat-like deck wave."
  else
    unset PX4_GZ_PLATFORM_VEL PX4_GZ_PLATFORM_HEADING_DEG PX4_GZ_TRAJECTORY_BASE_SPEED_MPS PX4_GZ_TRAJECTORY_SPEED_AMPLITUDE_MPS PX4_GZ_TRAJECTORY_SPEED_FREQUENCY_RADPS PX4_GZ_TRAJECTORY_SPEED_PHASE_RAD PX4_GZ_TRAJECTORY_LATERAL_AMPLITUDE_MPS PX4_GZ_TRAJECTORY_TURN_FREQUENCY_RADPS PX4_GZ_TRAJECTORY_TURN_PHASE_RAD PX4_GZ_WAVE_ROLL_DEG PX4_GZ_WAVE_PITCH_DEG PX4_GZ_WAVE_YAW_DEG PX4_GZ_WAVE_HEAVE_M PX4_GZ_WAVE_ROLL_FREQUENCY_RADPS PX4_GZ_WAVE_PITCH_FREQUENCY_RADPS PX4_GZ_WAVE_YAW_FREQUENCY_RADPS PX4_GZ_WAVE_HEAVE_FREQUENCY_RADPS PX4_GZ_WAVE_PHASE_RAD || true
  fi
  log "Starting PX4 SITL v1.17.0 with gz_x500_mono_cam_down in the ${WORLD_NAME} world."
  # PX4's interactive shell spins on an immediate EOF when launched in the
  # background. Keep stdin open with an inert pipe while preserving a separate
  # session/process group for reliable cleanup.
  # shellcheck disable=SC2016 # $1 expands inside the child bash, not here.
  # Start physically on the ground at a reproducible random point between the
  # visible 2 m and 7 m rings.  The QR must be acquired after takeoff.
  setsid bash -c 'cd "$1" && export PX4_GZ_WORLD="$3" PX4_GZ_MODEL_POSE="$2" && tail -f /dev/null | make px4_sitl gz_x500_mono_cam_down' \
    bash "$PX4_DIR" "$SPAWN_X,$SPAWN_Y,0,0,0,0" "$WORLD_NAME" >> "$PX4_LOG" 2>&1 &
  PX4_PID=$!
  record_pid px4 "$PX4_PID"

  if ! wait_for_gazebo_image_topic; then
    tail -n 80 "$PX4_LOG" >&2 || true
    fail 'Timed out waiting for a live gz.msgs.Image down-camera topic.'
  fi
  record_new_gazebo_gui
  log "Discovered Gazebo image topic: $IMAGE_TOPIC"
  [[ -n "$CAMERA_INFO_TOPIC" ]] && log "Discovered Gazebo camera-info topic: $CAMERA_INFO_TOPIC"
  write_bridge_config

  log 'Starting Gazebo-to-ROS 2 camera bridge.'
  start_bridge
  if ! wait_for_ros_image; then
    tail -n 80 "$BRIDGE_LOG" >&2 || true
    fail 'The ROS camera topic did not produce Image frames before the timeout.'
  fi
  if ! wait_for_px4_mavlink; then
    tail -n 80 "$PX4_LOG" >&2 || true
    fail 'PX4 MAVLink heartbeat endpoint did not become ready before the timeout.'
  fi
  log 'PX4 MAVLink endpoint is ready.'
  if [[ "$START_RQT" -eq 1 ]]; then
    log 'Validated /down_camera/image_raw frame delivery; starting rqt_image_view.'
    setsid ros2 run rqt_image_view rqt_image_view /down_camera/image_raw >> "$RQT_LOG" 2>&1 &
    RQT_PID=$!
    record_pid rqt_image_view "$RQT_PID"
  else
    log 'Validated /down_camera/image_raw frame delivery; rqt_image_view disabled for a clean third-person recording.'
  fi

  log 'Running. Gazebo and rqt_image_view should now be visible. Press Ctrl+C to stop.'
  wait "$PX4_PID"
}

main "$@"
